repos:
  - repo: local
    hooks:
      - id: taskfile precommit
        name: format
        entry: task qa:precommit --
        language: system
        pass_filenames: true
        stages: [commit]
