# https://taskfile.dev

version: "3"

dotenv:
  - "usecase.env"
  - ".env"

includes:
  setup: tasks/setup.yaml
  qa: tasks/qa.yaml
  training:docker:
    taskfile: tasks/docker.yaml
    vars:
      REPOSITORY_NAME: training
      REQUIREMENTS_FILE: requirements/training.txt
      BUILD_TARGET: training
  serving:docker:
    taskfile: tasks/docker.yaml
    vars:
      REPOSITORY_NAME: serving
      REQUIREMENTS_FILE: requirements/serving.txt
      BUILD_TARGET: serving
      IMAGE_SCANNING: true
  serving:
    taskfile: tasks/serving.yaml
  processing:docker:
    taskfile: tasks/docker.yaml
    vars:
      REPOSITORY_NAME: processing
      REQUIREMENTS_FILE: requirements/processing.txt
      BUILD_TARGET: processing

tasks:
  build-all:
    - task: training:docker:build
    - task: training:docker:push
    - task: serving:docker:build
    - task: serving:docker:push
    - task: processing:docker:build
    - task: processing:docker:push

  create-all-repositories:
    - task: training:docker:create-ecr-repository
    - task: serving:docker:create-ecr-repository
    - task: processing:docker:create-ecr-repository

  doc:
    desc: Create source code documentation
    summary: |
      Create source code documentation in docs using sphinx. Open ./docs/build/html/index.html to view output
    cmds:
      - sphinx-apidoc -f -o ./source/ ../src
      - make clean
      - make html
    dir: docs
